[package]
name = "crowdfunding"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
serde = "1.0.210"

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
